name: Senso
main: Main
version: 1.0
author: takumus
description: hello
depend: [Multiverse-Core]
commands:
  senso:
    description: senso
  game:
    description: senso
  stage:
    description: senso
  team:
    description: senso
  killmessage:
    description: senso